blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('posts/<int:id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.edit_post, name='edit_post'),
    path('posts/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    path('posts/<int:post_id>/edit_comment/<int:comment_id>/', views.edit_comment, name='edit_comment'),
    path('category/<slug:category_slug>/', views.category_posts, name='category_posts'),
    path('create/', views.create_post, name='create_post'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('posts/<int:post_id>/delete/', views.delete_post, name='delete_post'),
    path('posts/<int:post_id>/delete_comment/<int:comment_id>/', views.delete_comment, name='delete_comment'),
]

blogicum/urls.py
"""blogicum URL Configuration"""
from django.contrib import admin
from django.urls import include, path
from blog.views import signup
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('pages.urls', namespace='pages')),
    path('', include('blog.urls', namespace='blog')),
    path('auth/', include('django.contrib.auth.urls')),
    path('auth/registration/', signup, name='registration'),
]

handler404 = 'pages.views.page_not_found'
handler500 = 'pages.views.server_error'
handler403 = 'pages.views.csrf_failure'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/category_link.html
<a class="text-muted" href="{% url 'blog:category_posts' post.category.slug %}">
  {{ post.category.title }}
</a>

templates/includes/comments.html
{% if comments %}
  <div class="mt-4">
    <h5>Комментарии</h5>
    {% for comment in comments %}
      <div class="media mb-4">
        <div class="media-body">
          <h6 class="mt-0">
            <a href="{% url 'blog:profile' comment.author.username %}" name="comment_{{ comment.id }}">
              @{{ comment.author.username }}
            </a>
          </h6>
          <small class="text-muted">{{ comment.created_at }}</small>
          <br>
          {{ comment.text|linebreaksbr }}
        </div>
        {% if user == comment.author %}
          <span class="text-muted">(ваш комментарий)</span>
        {% endif %}
      </div>
    {% endfor %}
  </div>
{% else %}
  <div class="mt-4">
    <h5>Комментарии</h5>
    <p class="text-muted">Комментариев пока нет</p>
  </div>
{% endif %}

templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© Блогикум</p>    
</footer>

templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'blog:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        Блогикум
      </a>
      {% with request.resolver_match.view_name as view_name %}
        <ul class="nav  nav-pills">
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'pages:about' %} text-white {% endif %}" href="{% url 'pages:about' %}">
              О проекте
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'pages:rules' %} text-white {% endif %}" href="{% url 'pages:rules' %}">
              Правила
            </a>
          </li>
          {% if user.is_authenticated %}
            <div class="btn-group" role="group" aria-label="Basic outlined example">
              <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
                  href="{% url 'blog:create_post' %}">Написать пост</a></button>
              <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
                  href="{% url 'blog:profile' user.username %}">{{ user.username }}</a></button>
              <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
                  href="{% url 'logout' %}">Выйти</a></button>
            </div>
          {% else %}
            <div class="btn-group" role="group" aria-label="Basic outlined example">
              <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
                  href="{% url 'login' %}">Войти</a></button>
              <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
                  href="{% url 'registration' %}">Регистрация</a></button>
            </div>
          {% endif %}
        </ul>
      {% endwith %}
    </div>
  </nav>
</header>

templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1">Первая</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Назад</a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">Вперед</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

templates/includes/post_card.html
<div class="col d-flex justify-content-center">
  <div class="card" style="width: 40rem;">
    <div class="card-body">
      {% if post.image %}
        <a href="{{ post.image.url }}" target="_blank">
          <img class="border-3 rounded img-fluid img-thumbnail mb-2 mx-auto d-block" src="{{ post.image.url }}">
        </a>
      {% endif %}
      <h5 class="card-title">{{ post.title }}</h5>
      <h6 class="card-subtitle mb-2 text-muted">
        <small>
          {% if not post.is_published %}
            <p class="text-danger">Пост снят с публикации админом</p>
          {% elif not post.category.is_published %}
            <p class="text-danger">Выбранная категория снята с публикации админом</p>
          {% endif %}
          {{ post.pub_date|date:"d E Y, H:i" }} | {% if post.location and post.location.is_published %}{{ post.location.name }}{% else %}Планета Земля{% endif %}<br>
          От автора <a class="text-muted" href="{% url 'blog:profile' post.author.username %}">@{{ post.author.username }}</a> в
          категории {% include "includes/category_link.html" %}
        </small>
      </h6>
      <p class="card-text">{{ post.text|truncatewords:10 }}</p>
      <a href="{% url 'blog:post_detail' post.id %}" class="card-link">Читать полный текст</a>
      <a href="{% url 'blog:post_detail' post.id %}" class="card-link text-muted">Комментарии ({{ post.comments.count }})</a>
    </div>
  </div>
</div>